export const INCREASE_TOTAL_LIKES = "INCREASE_TOTAL_LIKES"
export const DECREASE_TOTAL_LIKES = "DECREASE_TOTAL_LIKES"
export const INCREASE_TOTAL_LIKES_BY_AMOUNT = "INCREASE_TOTAL_LIKES_BY_AMOUNT"
export const CHANGE_ROLE = "CHANGE_ROLE"